device_id: xczu67dr
processor:
    psu_cortexa53_0:
        arch: aarch64
        ip_name: psu_cortexa53
        slaves_strings: zynqmp_reset pinctrl0 gic_a53 fpd_dma_chan1 fpd_dma_chan2 fpd_dma_chan3 fpd_dma_chan4 fpd_dma_chan5 fpd_dma_chan6 fpd_dma_chan7 fpd_dma_chan8 lpd_dma_chan1 lpd_dma_chan2 lpd_dma_chan3 lpd_dma_chan4 lpd_dma_chan5 lpd_dma_chan6 lpd_dma_chan7 lpd_dma_chan8 mc gem3 gpio i2c0 i2c1 ocm perf_monitor_ocm perf_monitor_ddr perf_monitor_cci perf_monitor_lpd qspi psgtr rtc sdhci1 smmu ttc0 ttc1 ttc2 ttc3 uart0 usb0 dwc3_0 watchdog0 lpd_watchdog xilinx_ams ams_ps ams_pl coresight_0 csudma_0 ipi0 psu_r5_tcm_ram_global psu_r5_1_btcm_global psu_r5_1_atcm_global psu_r5_0_btcm_global psu_r5_0_atcm_global psu_pmu_global_0 psu_mbistjtag psu_rsa psu_efuse psu_csu_0 psu_fpd_gpv psu_cci_gpv psu_fpd_slcr_secure psu_fpd_slcr psu_smmu_reg psu_cci_reg psu_fpd_xmpu_cfg psu_apu psu_fpd_xmpu_sink psu_siou psu_afi_5 psu_afi_4 psu_afi_3 psu_afi_2 psu_afi_1 psu_afi_0 psu_crf_apb psu_ddr_qos_ctrl psu_ddr_phy psu_ddr_xmpu5_cfg psu_ddr_xmpu4_cfg psu_ddr_xmpu3_cfg psu_ddr_xmpu2_cfg psu_ddr_xmpu1_cfg psu_ddr_xmpu0_cfg psu_ocm_xmpu_cfg psu_lpd_xppu_sink psu_afi_6 psu_rpu psu_crl_apb psu_lpd_slcr_secure psu_lpd_slcr psu_iou_scntrs psu_iou_scntr psu_iousecure_slcr psu_iouslcr_0 lpd_xppu cmac_axi_gpio_0 cmac_axi_mcdma_0 cmac_cmac_usplus_0 other_perph_axi_timer_1 zynq_ps_bram_axi_bram_ctrl_0
        slaves:
            axi_bram_0:
                device_type: memory
                ip_name: axi_bram
                baseaddr: '0xa0000000'
                highaddr: '0xa0002000'
            psu_ocm_0:
                device_type: memory
                ip_name: psu_ocm
                baseaddr: '0xfffc0000'
                highaddr: '0x100000000'
            psu_ddr_0:
                device_type: memory
                ip_name: psu_ddr
                baseaddr: '0x0'
                highaddr: '0x7ff00000'
            psu_ddr_1:
                device_type: memory
                ip_name: psu_ddr
                baseaddr: '0x800000000'
                highaddr: '0x880000000'
            psu_qspi_linear_0:
                device_type: linear_flash
                ip_name: psu_qspi_linear
                baseaddr: '0xc0000000'
                highaddr: '0xe0000000'
            uart0:
                device_type: serial
                ip_name: psu_uart
                baseaddr: '0xff000000'
            gem3:
                device_type: ethernet
                ip_name: psu_ethernet
            sdhci1:
                device_type: sd
                ip_name: psu_sd
            qspi:
                device_type: flash
                ip_name: psu_qspi
            gic_a53:
                ip_name: psu_acpu_gic
            fpd_dma_chan1:
                ip_name: psu_gdma
            fpd_dma_chan2:
                ip_name: psu_gdma
            fpd_dma_chan3:
                ip_name: psu_gdma
            fpd_dma_chan4:
                ip_name: psu_gdma
            fpd_dma_chan5:
                ip_name: psu_gdma
            fpd_dma_chan6:
                ip_name: psu_gdma
            fpd_dma_chan7:
                ip_name: psu_gdma
            fpd_dma_chan8:
                ip_name: psu_gdma
            lpd_dma_chan1:
                ip_name: psu_adma
            lpd_dma_chan2:
                ip_name: psu_adma
            lpd_dma_chan3:
                ip_name: psu_adma
            lpd_dma_chan4:
                ip_name: psu_adma
            lpd_dma_chan5:
                ip_name: psu_adma
            lpd_dma_chan6:
                ip_name: psu_adma
            lpd_dma_chan7:
                ip_name: psu_adma
            lpd_dma_chan8:
                ip_name: psu_adma
            mc:
                ip_name: psu_ddrc
            gpio:
                ip_name: psu_gpio
            i2c0:
                ip_name: psu_i2c
            i2c1:
                ip_name: psu_i2c
            ocm:
                ip_name: psu_ocm
            perf_monitor_ocm:
                ip_name: psu_apm
            perf_monitor_ddr:
                ip_name: psu_apm
            perf_monitor_cci:
                ip_name: psu_apm
            perf_monitor_lpd:
                ip_name: psu_apm
            psgtr:
                ip_name: psu_serdes
            rtc:
                ip_name: psu_rtc
            smmu:
                ip_name: psu_smmu_gpv
            ttc0:
                ip_name: psu_ttc
            ttc1:
                ip_name: psu_ttc
            ttc2:
                ip_name: psu_ttc
            ttc3:
                ip_name: psu_ttc
            usb0:
                ip_name: psu_usb
            dwc3_0:
                ip_name: psu_usb_xhci
            watchdog0:
                ip_name: psu_wdt
            lpd_watchdog:
                ip_name: psu_wdt
            xilinx_ams:
                ip_name: psu_ams
            coresight_0:
                ip_name: psu_coresight_0
            csudma_0:
                ip_name: psu_csudma
            ipi0:
                ip_name: psu_ipi
            psu_r5_tcm_ram_global:
                ip_name: psu_r5_tcm_ram
            psu_r5_1_btcm_global:
                ip_name: psu_r5_1_btcm_global
            psu_r5_1_atcm_global:
                ip_name: psu_r5_1_atcm_global
            psu_r5_0_btcm_global:
                ip_name: psu_r5_0_btcm_global
            psu_r5_0_atcm_global:
                ip_name: psu_r5_0_atcm_global
            psu_pmu_global_0:
                ip_name: psu_pmu_global_0
            psu_mbistjtag:
                ip_name: psu_mbistjtag
            psu_rsa:
                ip_name: psu_rsa
            psu_efuse:
                ip_name: psu_efuse
            psu_csu_0:
                ip_name: psu_csu
            psu_fpd_gpv:
                ip_name: psu_fpd_gpv
            psu_cci_gpv:
                ip_name: psu_cci_gpv
            psu_fpd_slcr_secure:
                ip_name: psu_fpd_slcr_secure
            psu_fpd_slcr:
                ip_name: psu_fpd_slcr
            psu_smmu_reg:
                ip_name: psu_smmu_reg
            psu_cci_reg:
                ip_name: psu_cci_reg
            psu_fpd_xmpu_cfg:
                ip_name: psu_fpd_xmpu_cfg
            psu_apu:
                ip_name: psu_apu
            psu_fpd_xmpu_sink:
                ip_name: psu_fpd_xmpu_sink
            psu_siou:
                ip_name: psu_siou
            psu_afi_5:
                ip_name: psu_afi
            psu_afi_4:
                ip_name: psu_afi
            psu_afi_3:
                ip_name: psu_afi
            psu_afi_2:
                ip_name: psu_afi
            psu_afi_1:
                ip_name: psu_afi
            psu_afi_0:
                ip_name: psu_afi
            psu_crf_apb:
                ip_name: psu_crf_apb
            psu_ddr_qos_ctrl:
                ip_name: psu_ddr_qos_ctrl
            psu_ddr_phy:
                ip_name: psu_ddr_phy
            psu_ddr_xmpu5_cfg:
                ip_name: psu_ddr_xmpu5_cfg
            psu_ddr_xmpu4_cfg:
                ip_name: psu_ddr_xmpu4_cfg
            psu_ddr_xmpu3_cfg:
                ip_name: psu_ddr_xmpu3_cfg
            psu_ddr_xmpu2_cfg:
                ip_name: psu_ddr_xmpu2_cfg
            psu_ddr_xmpu1_cfg:
                ip_name: psu_ddr_xmpu1_cfg
            psu_ddr_xmpu0_cfg:
                ip_name: psu_ddr_xmpu0_cfg
            psu_ocm_xmpu_cfg:
                ip_name: psu_ocm_xmpu_cfg
            psu_lpd_xppu_sink:
                ip_name: psu_lpd_xppu_sink
            psu_afi_6:
                ip_name: psu_afi
            psu_rpu:
                ip_name: psu_rpu
            psu_crl_apb:
                ip_name: psu_crl_apb
            psu_lpd_slcr_secure:
                ip_name: psu_lpd_slcr_secure
            psu_lpd_slcr:
                ip_name: psu_lpd_slcr
            psu_iou_scntrs:
                ip_name: psu_iou_scntrs
            psu_iou_scntr:
                ip_name: psu_iou_scntr
            psu_iousecure_slcr:
                ip_name: psu_iousecure_slcr
            psu_iouslcr_0:
                ip_name: psu_iouslcr
            lpd_xppu:
                ip_name: psu_lpd_xppu
            cmac_axi_gpio_0:
                ip_name: axi_gpio
            cmac_axi_mcdma_0:
                ip_name: axi_mcdma
            cmac_cmac_usplus_0:
                ip_name: cmac_usplus
            other_perph_axi_timer_1:
                ip_name: axi_timer
            zynq_ps_bram_axi_bram_ctrl_0:
                ip_name: axi_bram_ctrl
